// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzP_a-Sh-_GPwzwa4udXoVgE__4G62K0',
    appId: '1:269173309474:web:574eda7299792b4223ca7b',
    messagingSenderId: '269173309474',
    projectId: 'firestream-c856a',
    authDomain: 'firestream-c856a.firebaseapp.com',
    storageBucket: 'firestream-c856a.appspot.com',
    measurementId: 'G-67XJXG971N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmlmEVYg-PmLRE-zbF7BOHjdhIOWA36c',
    appId: '1:269173309474:android:a969f4b0db3faad123ca7b',
    messagingSenderId: '269173309474',
    projectId: 'firestream-c856a',
    storageBucket: 'firestream-c856a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5oPWxrE1FwihRFS1bqD9p_RhWRRyDIwE',
    appId: '1:269173309474:ios:743214c3971cedb523ca7b',
    messagingSenderId: '269173309474',
    projectId: 'firestream-c856a',
    storageBucket: 'firestream-c856a.appspot.com',
    iosBundleId: 'com.example.firestream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5oPWxrE1FwihRFS1bqD9p_RhWRRyDIwE',
    appId: '1:269173309474:ios:743214c3971cedb523ca7b',
    messagingSenderId: '269173309474',
    projectId: 'firestream-c856a',
    storageBucket: 'firestream-c856a.appspot.com',
    iosBundleId: 'com.example.firestream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnzP_a-Sh-_GPwzwa4udXoVgE__4G62K0',
    appId: '1:269173309474:web:855494bb1d8722f123ca7b',
    messagingSenderId: '269173309474',
    projectId: 'firestream-c856a',
    authDomain: 'firestream-c856a.firebaseapp.com',
    storageBucket: 'firestream-c856a.appspot.com',
    measurementId: 'G-78QVJETZJ1',
  );
}
